enum TAB {
  CLOSE_TAB = "TAB_CLOSE_TAB",
  CLOSE_ALL_TABS = "TAB_CLOSE_ALL_TABS",
  CLOSE_LEFT_TABS = "TAB_CLOSE_LEFT_TABS",
  CLOSE_RIGHT_TABS = "TAB_CLOSE_RIGHT_TABS",
  CLOSE_SAVED_TABS = "TAB_CLOSE_SAVED_TABS"
}

export default TAB;