enum Workbench {
  // FOR REDUCERS
  OPEN_WORKBENCH = 'WORKBENCH_OPEN_WORKBENCH',
  CLOSE_WORKBENCH = 'WORKBENCH_CLOSE_WORKBENCH',
  // FOR SAGA
  TOGGLE_WORKBENCH = 'WORKBENCH_TOGGLE_WORKBENCH'
}

export default Workbench;
