// Generated by @yuxino/desktop-installer. Edit the shared source repository.
// Offline, pinned presentation bundle. No network or downloaded JavaScript.
import { createHash } from 'node:crypto';
import { readFileSync, mkdirSync, writeFileSync, renameSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { brotliDecompressSync } from 'node:zlib';

export const themeDirectory = fileURLToPath(new URL('.', import.meta.url));
export const fileNames = ['English.nsh', 'Japanese.nsh', 'SimpChinese.nsh', 'preview.nsi', 'sidebar.bmp', 'theme.nsh'];
export const digest = data => createHash('sha256').update(data).digest('hex');
const maximumBundleSize = 8 * 1024 * 1024;
const width = 656, height = 1256;
const bitmapSize = 54 + ((width * 3 + 3) & ~3) * height;

export function decodeBundle(compressed, lock) {
  if (lock?.format !== 'yuxino-installer-lock-v2' || !/^[a-z][a-z0-9-]*$/.test(lock.product ?? '') ||
      !/^\d+\.\d+\.\d+$/.test(lock.version ?? '') ||
      !Number.isInteger(lock.size) || lock.size < 1 || lock.size > maximumBundleSize ||
      !Number.isInteger(lock.unpackedSize) || lock.unpackedSize < 1 || lock.unpackedSize > maximumBundleSize ||
      !/^[a-f0-9]{64}$/.test(lock.sha256 ?? '') ||
      compressed.length !== lock.size || digest(compressed) !== lock.sha256) {
    throw new Error('Invalid or corrupt installer bundle');
  }
  const bytes = brotliDecompressSync(compressed, { maxOutputLength: lock.unpackedSize });
  if (bytes.length !== lock.unpackedSize) throw new Error('Invalid installer bundle size');
  const pack = JSON.parse(bytes.toString('utf8'));
  if (pack.format !== 'yuxino-installer-v2' || pack.product !== lock.product || pack.version !== lock.version ||
      JSON.stringify(Object.keys(pack.files ?? {}).sort()) !== JSON.stringify(fileNames)) {
    throw new Error('Wrong product or incomplete installer bundle');
  }
  const files = {};
  for (const name of fileNames) {
    const entry = pack.files[name];
    const limit = name === 'sidebar.bmp' ? bitmapSize : 64 * 1024;
    if (!Number.isInteger(entry?.size) || entry.size < 1 || entry.size > limit ||
        typeof entry.data !== 'string' || entry.data.length > Math.ceil(limit / 3) * 4 ||
        !/^[a-f0-9]{64}$/.test(entry.sha256 ?? '')) throw new Error(`Invalid installer entry: ${name}`);
    const data = Buffer.from(entry.data, 'base64');
    if (data.toString('base64') !== entry.data || data.length !== entry.size || digest(data) !== entry.sha256) {
      throw new Error(`Corrupt installer entry: ${name}`);
    }
    files[name] = data;
  }
  const b = files['sidebar.bmp'];
  if (b.length !== bitmapSize || b.toString('ascii', 0, 2) !== 'BM' || b.readUInt32LE(2) !== bitmapSize ||
      b.readUInt32LE(10) !== 54 || b.readUInt32LE(14) !== 40 || b.readInt32LE(18) !== width ||
      b.readInt32LE(22) !== height || b.readUInt16LE(26) !== 1 || b.readUInt16LE(28) !== 24 ||
      b.readUInt32LE(30) !== 0) throw new Error('Invalid 4x full-color installer bitmap');
  return files;
}

export function loadBundle(directory = themeDirectory) {
  const lock = JSON.parse(readFileSync(join(directory, 'theme.lock.json'), 'utf8'));
  return decodeBundle(readFileSync(join(directory, 'theme.bundle.br')), lock);
}

export function buildTheme(outputDirectory = join(themeDirectory, 'generated'), check = false, directory = themeDirectory) {
  // Validate every byte before writing any output. File names are a fixed allow-list.
  const files = loadBundle(directory);
  if (!check) mkdirSync(outputDirectory, { recursive: true });
  for (const [name, data] of Object.entries(files)) {
    const destination = join(outputDirectory, name);
    if (check) {
      if (!readFileSync(destination).equals(data)) throw new Error(`Stale installer file: ${name}`);
    } else {
      const temporary = `${destination}.${process.pid}.tmp`;
      writeFileSync(temporary, data);
      renameSync(temporary, destination);
    }
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const args = process.argv.slice(2);
    if (args.length > 1 || args.some(a => a !== '--check')) throw new Error('Usage: build.mjs [--check]');
    buildTheme(undefined, args.includes('--check'));
    console.log('Shared installer verified: offline, full-color 4x, English / 中文 / 日本語.');
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
